import { Module } from '@nestjs/common';
import { AcademicController } from './academic.controller';
import { AcademicService } from './academic.service';
import { DatabaseModule } from '@app/database';
import {
  DuracionesController, DuracionesService,
  VersionesController, VersionesService,
  TiposController, TiposService,
  ModalidadesController, ModalidadesService,
  TurnosController, TurnosService,
  InscripcionesController, InscripcionesService,
  BauchersController, BauchersService,
  CalificacionesController, CalificacionesService,
  EventosController, EventosService,
  EventosTiposController, EventosTiposService,
  EventosInscripcionesController, EventosInscripcionesService,
  EventosPersonasController, EventosPersonasService,
  EstadosInscripcionController, EstadosInscripcionService,
  ProgramasController, ProgramasService,
  ModulosController, ModulosService,
  ProgramaDosController, ProgramaDosService,
  ProgramaModuloDosController, ProgramaModuloDosService,
  ProgramaBaseController,
  AsignacionesController, AsignacionesService,
  BlogsController, BlogsService,
  ComunicadosController, ComunicadosService,
} from './academic-crud.controllers';
import { PublicController } from './public.controller';

@Module({
  imports: [DatabaseModule],
  controllers: [
    AcademicController,
    ProgramasController,
    ModulosController,
    ProgramaDosController,
    ProgramaBaseController,
    ProgramaModuloDosController,
    DuracionesController,
    VersionesController,
    TiposController,
    ModalidadesController,
    TurnosController,
    InscripcionesController,
    BauchersController,
    CalificacionesController,
    EventosController,
    EventosTiposController,
    EventosInscripcionesController,
    EventosPersonasController,
    EstadosInscripcionController,
    AsignacionesController,
    BlogsController,
    ComunicadosController,
    PublicController,
  ],
  providers: [
    AcademicService,
    ProgramasService,
    ModulosService,
    ProgramaDosService,
    ProgramaModuloDosService,
    DuracionesService,
    VersionesService,
    TiposService,
    ModalidadesService,
    TurnosService,
    InscripcionesService,
    BauchersService,
    CalificacionesService,
    EventosService,
    EventosTiposService,
    EventosInscripcionesService,
    EventosPersonasService,
    EstadosInscripcionService,
    AsignacionesService,
    BlogsService,
    ComunicadosService,
  ],
})
export class AcademicModule { }
