export class Profe {
  constructor(
    public id: string,
    public nombre: string,
    public nombreAbreviado: string | null,
    public logoPrincipal: string | null,
    public descripcion: string,
    public mision: string,
    public vision: string,
    public sobreNosotros: string,
    public actividad: string,
    public fechaCreacion: Date,
    public ubicacion: string,
    public correo: string | null,
    public celular: string | null,
    public telefono: string | null,
    public pagina: string | null,
    public facebook: string | null,
    public tiktok: string | null,
    public youtube: string | null,
    public latitud: number | null,
    public longitud: number | null,
    public banner: string | null,
    public afiche: string | null,
    public convocatoria: string | null,
    public imagen: string | null,
    public color: string | null,
    public colorSecundario: string | null,
    public mantenimiento: boolean,
    public estado: string,
  ) {}
}
